'use client'
import type { Metadata } from 'next'
import { Analytics } from '@vercel/analytics/react';
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './_componets/Header'
import Footer from './_componets/Footer'
import { ClerkProvider } from '@clerk/nextjs'
import { Cartcontext } from './_context/Cartcontext'
import { useState } from 'react'
import { SpeedInsights } from '@vercel/speed-insights/next';
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [cart, setCart] = useState([])
  return (
    <ClerkProvider>
      <Cartcontext.Provider value={{ cart, setCart }}>
        <html lang="en">
          <body className={inter.className}><Header />{children}
            <Analytics />
            <SpeedInsights />
            <Footer /></body>
        </html>
      </Cartcontext.Provider>
    </ClerkProvider>
  )
}
